#define MONS_CUSTOM_CONFIG

#define MONS_MAT_TYPE arma::mat

#define MONS_FUNCTION_TYPE mlpack::FFN<mlpack::MeanSquaredError>

#define MONS_PREDICTOR_TYPE MONS_MAT_TYPE
#define MONS_RESPONSE_TYPE MONS_MAT_TYPE
#define MONS_WEIGHT_TYPE MONS_SEQUENCE_LENGTH_TYPE
